### ISSUE TITLE
Add VMC Ecocomfort 2.0 Smart support 

### ISSUE THREAD

**Issue by lepo80** [ruizmarc/homebridge-intelliclima#2]
**Describe Your Problem:**

**Logs:**
[10/7/2024, 5:57:26 PM] [homebridge-intelliclima] Obtaining Intelliclima house for user: XXXXX
[10/7/2024, 5:57:27 PM] [homebridge-intelliclima] Error while getting device: 36171
TypeError: Cannot read properties of undefined (reading 'id')
    at Function.mapIntelliClimaDeviceResponseToThermostatInfo (/config/node_modules/homebridge-intelliclima/src/accessories/ThermostatAccessory.ts:63:22)
    at IntelliClimaPlatform.discoverDevices (/config/node_modules/homebridge-intelliclima/src/platform/IntelliClimaPlatform.ts:73:49)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at HomebridgeAPI.<anonymous> (/config/node_modules/homebridge-intelliclima/src/platform/IntelliClimaPlatform.ts:41:7)
```
Show the Homebridge logs here, remove any sensitive information.
```

**Plugin Config:**

```json
Show your Homebridge config.json here, remove any sensitive information.
```

**Screenshots:**

**Environment:**

* **Plugin Version**:
* **Homebridge Version**: 
* **Node.js Version**: 
* **NPM Version**: 
* **Operating System**:

**Comment by ruizmarc** [comment]
Hi,

It seems Ecocomfort has a different device mapping from C800WiFi.

As Intelliclima has no public API with documentation, I cannot add new devices unless I own them to get all requests and responses from the device API through the App. 

If you own one, you can open a PR with the changes required to map and control the device. I normally use a proxy to intercept the requests and the responses from the App.

If you have any doubt or need support, I leave this issue open for a while so you can share your problems

**Comment by lepo80** [comment]
Hi, I get the concept, but I don't have any experience to sniff the app traffic.
Do you have any suggestions? I use Android device for interlliclima+ app.
Thx

**Comment by ruizmarc** [comment]
I normally use a proxy on my computer and connect my phone to the proxy. You have a lot of proxy apps out there, proxyman, burp... use your favourite :)

**Comment by lepo80** [comment]
Hi, I tried to use proxyman... using my android device and connecting via proxyman. but i met the SSL issue even if i installed the right certificate into my mobile.
do you have a simply procedure, please?

**Comment by ruizmarc** [comment]
Hi, 

To intercept any HTTPS request you will always need to trust the certificate in the proxy... there is no other way as far as I know. 

I'm using iOS and I had no problems to install the certificate and set as trusted. Check that in addition to install the certificate in the device, you have trusted it (normally it is installed as untrusted)

**Comment by lepo80** [comment]
the certificate is trusted at user level, may be that should be installed at system level? but I don't have a rooted device.

**Comment by ruizmarc** [comment]
I don't know in Android, but in iOS I do it at user level

**Comment by LakiTom** [comment]
@ruizmarc Hello, if you want to expand your plugin with the Ecocomfort 2.0 Smart API I have some and I can pick up the API requests with proxyman and possibly test the changes. If you are interested let me know, it could be very useful for all owners who currently have an app with various bugs and not functional.

**Comment by miclausandrei** [comment]
@LakiTom Hello, i'm also intrested for the API requests. I'm trying to create a custom component for home assistant to integrate this ventilation unit and i'm struggling to intercept the traffic. Is it possible to send me the API requests? 

Thanks.

**Comment by ruizmarc** [comment]
Hi @LakiTom 

Without having a device to test, it is very difficult to add support to it, even having the request. I encourage you to open a PR, I will be happy to review it and help :)

**Comment by LakiTom** [comment]
@miclausandrei, No problem, first I try to learn how to use proxyman to correctly read the API that I currently intercept, because i never read calls before.

@ruizmarc, Thank you very much. I've never opened a PR, I've always worked with a small team, without using these features, so I hope I don't make a mess.
